const $=s=>document.querySelector(s);
const messages={
zh:{skip:'跳至文章',brand:'Galaxy<span class="logo-dot"></span>',resume:'簡歷 <span class="tiny">PDF</span>',name:'高天駿',work:'作品',about:'關於',blog:'隨筆',contact:'聯絡',eyebrow:'04 — 隨筆',headline:'一些感受，<br><span>慢慢記下。</span>',deck:'關於日常、想法，和還沒有答案的事。',browse:'閱讀隨筆 <span aria-hidden="true" class="action-arrow">↘</span>',published:'已發表',note:'不必完整，也值得記錄。',byline:'高天駿的個人隨筆',backHome:'← 回到首頁',close:'關閉 ✕',emptyTitle:'故事，慢慢寫。',emptyBody:'第一篇隨筆，正在醞釀中。',error:'文章暫時未能載入，請稍後重新整理。',minutes:'分鐘閱讀'},
en:{skip:'Skip to entries',brand:'Galaxy<span class="logo-dot"></span>',resume:'Résumé <span class="tiny">PDF</span>',name:'Tianjun Gao',work:'Work',about:'About',blog:'Journal',contact:'Contact',eyebrow:'04 — JOURNAL',headline:'Little thoughts.<br><span>Room to grow.</span>',deck:'Everyday moments, ideas, and questions still unfolding.',browse:'Read the journal <span aria-hidden="true" class="action-arrow">↘</span>',published:'Published',note:'Unfinished thoughts belong here, too.',byline:'A journal by Tianjun Gao',backHome:'← Back home',close:'Close ✕',emptyTitle:'A story in the making.',emptyBody:'The first entry is on its way.',error:'Entries could not be loaded. Please refresh in a moment.',minutes:'min read'}
};
let lang='zh',posts=[],loaded=false;try{lang=localStorage.getItem('tianjun-language')==='en'?'en':'zh';}catch{}
const t=k=>messages[lang][k];const reader=$('#reader');
function date(s){return new Intl.DateTimeFormat(lang==='zh'?'zh-Hant':'en',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(s));}
function render(){const list=$('#post-list');list.replaceChildren();$('#published-count').textContent=String(posts.length).padStart(2,'0');if(!loaded)return;if(!posts.length){const el=document.createElement('div');el.className='empty-state';el.innerHTML='<span class="empty-mark" aria-hidden="true"></span><div><h2></h2><p></p></div>';el.querySelector('h2').textContent=t('emptyTitle');el.querySelector('p').textContent=t('emptyBody');list.append(el);}for(const p of posts){const row=document.createElement('button');row.type='button';row.className='post-row';row.innerHTML='<span class="post-date"></span><div><h3></h3><p></p></div><span class="row-arrow" aria-hidden="true">↗</span>';row.querySelector('.post-date').textContent=date(p.published_at);row.querySelector('h3').textContent=p.title;row.querySelector('p').textContent=p.body.trim().slice(0,240);row.onclick=()=>open(p);list.append(row);}}
function open(p){$('#read-title').textContent=p.title;$('#read-body').textContent=p.body;const minutes=Math.max(1,Math.ceil((p.body.match(/[\u3400-\u9fff]/g)||[]).length/400+p.body.replace(/[\u3400-\u9fff]/g,' ').trim().split(/\s+/).length/200));$('#read-meta').textContent=date(p.published_at)+' · '+minutes+' '+t('minutes');reader.showModal();document.body.style.overflow='hidden';history.replaceState(null,'','#post='+p.id);}
function close(){reader.close();document.body.style.overflow='';history.replaceState(null,'',location.pathname);}
$('#close-reader').onclick=close;reader.addEventListener('cancel',e=>{e.preventDefault();close();});
function language(value){lang=value;document.documentElement.lang=lang==='zh'?'zh-Hant':'en';document.title=lang==='zh'?'Galaxy — 隨筆':'Galaxy — Journal';document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n));document.querySelector('.resume-link').href=lang==='zh'?'../Tianjun-Gao-Resume-ZH.pdf':'../Tianjun-Gao-Resume.pdf';document.querySelector('header .wordmark').setAttribute('aria-label',lang==='zh'?'Galaxy 首頁':'Galaxy home');document.querySelectorAll('[data-language]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.language===lang));try{localStorage.setItem('tianjun-language',lang);}catch{}render();}
for(const b of document.querySelectorAll('[data-language]'))b.onclick=()=>language(b.dataset.language);
language(lang);
fetch('posts.json?v=8177c652457c', {cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{posts=data;loaded=true;render();const id=new URLSearchParams(location.hash.slice(1)).get('post');const p=posts.find(p=>p.id===id);if(p)open(p);}).catch(()=>{$('#list-status').textContent=t('error');});
